### PR TITLE
Use some macros to simplify our code

### PR DESCRIPTION
**Pull request by alunux**

### CODE REVIEW

**Comment by chergert** [comment]
Make sure that autoptr/autofree variables are assigned to NULL and then this looks good. I don't want to see people using those API's w/o explicit initialization, too prone to error.

**Comment by alunux** [comment]
@chergert Done :)

**Comment by chergert** [comment]
Thanks!

**Comment by alunux** [comment]
@chergert It's not easy to find example about GObject. Thank you so much for providing us these great examples.

**Pull request merged**
